language: go

go:
    - "1.10"

env:
    global:
        - SSH_KEY="travis_key"
        - GIT_NAME="Daniel Morgan"
        - GIT_EMAIL="me@plod.tv"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"

before_install:
    - openssl aes-256-cbc -K $encrypted_82130ec8988c_key -iv $encrypted_82130ec8988c_iv -in travis_key.enc -out travis_key -d

before_script:
    - go get -u -v github.com/magefile/mage
    - go get -u -v github.com/spf13/hugo
    - cd $GOPATH/src/github.com/spf13/hugo && mage vendor && go install
    - cd $HOME/gopath/src/github.com/plod/plod.github.io

script:
    - hugo

after_success:
    - echo "plod.tv" > ./public/CNAME
    - ./scripts/deploy.sh
