baseurl = "https://plod.tv"
languageCode = "en-gb"
title = "plod.tv"
newContentEditor = "nano"
theme = "startbootstrap-clean-blog"
pygmentsStyle = "colorful"
canonifyurls = true
paginate = 10
disqusShortname = "plodtv"

[author]
  name = "Daniel T. Morgan"

[params]
  DateForm = "Monday Jan 2 2006"
  Description = "My personal corner of the ether"
  Author = "Daniel T. Morgan"
  email = "daniel@morgan.cymru"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/plodtv"
[[params.social]]
  title = "github"
  url = "https://github.com/plod"
[[params.social]]
  title = "instagram"
  url = "https://www.instagram.com/plodtv/"
[[params.social]]
  title = "google-plus"
  url = "https://plus.google.com/u/0/114867298714740005580"

[[menu.main]]
  name = "about"
  identifier = "about"
  url = "/about/"
  weight = -200
  
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
  
[[menu.main]]
  name = "Contact Me"
  url = "/contact/"
  weight = -170
