baseurl = "https://plod.tv/"
languageCode = "en-gb"
title = "plod.tv"
newContentEditor = "vim"
theme = "startbootstrap-clean-blog"
pygmentsStyle = "colorful"
canonifyurls = true
paginate = 10
disqusShortname = "plodtv"
googleAnalytics = "UA-21314793-1" # delete or comment to disable Google Analytics JS generation

[author]
  name = "Daniel T. Morgan"

[params]
  DateForm = "Monday Jan 2 2006"
  Description = "My personal corner of the ether"
  Author = "Daniel T. Morgan"
  email = "daniel@morgan.cymru"
  Ganalytics = "UA-21314793-1"
  postSummariesFrontPage = 4 

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/plodtv"
[[params.social]]
  title = "github"
  url = "https://github.com/plod"
[[params.social]]
  title = "instagram"
  url = "https://www.instagram.com/plodtv/"
[[params.social]]
  title = "google-plus"
  url = "https://plus.google.com/u/0/114867298714740005580"
[[params.social]]
  title = "linux"
  url = "https://launchpad.net/~me-plod"
[[params.social]]
  title = "linkedin"
  url = "http://uk.linkedin.com/in/plodtv"
[[params.social]]
  title = "free-code-camp"
  url = "https://www.freecodecamp.com/plod"
[[params.social]]
  title = "code"
  url = "https://www.codeschool.com/users/plod"
  
  

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = -200
  
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -10
  
[[menu.main]]
  name = "Contact Me"
  url = "/contact/"
  weight = -170
